language: java
jdk:
- openjdk13
os:
- linux
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- chmod +x gradlew
branches:
  only:
  - master
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: gSarmxWmODzzo75aj9iOIFYUa7FjGpcoYQu3ZB4ocwvo9suWC/bSTaQqMmXeJgQ/xnaFb4iroP0u0tdpoo7e/U/cuMNHcqCKzWx3mc/YcqdxOpdB3D4CIN6V1uMDTr5uD2IDrBE6FK+IOQecs3wCLAMbt0AHlN+PPzwyg39ghn3HZyQdwYTzLyWdc/Kqy8xIhC+opY5AaN3mD61kQozggsjuHHUfUo7l3J08YPEkNtW0swiMTQgc6bJrG2NVOfWCma7FexWeSGQ3uvfYeHQ5loaAq8w5wtFqpnvfnlkqQroxjqzb2KI7By26I8OW1/1yq0zX2GH5c8NmsRKKpRzq8MYO8COnGomck1Epx/1xmbv6tnYyUvVGRPsD4wFEdShoXdAvwgQERoSVYV2QNUlPqJoeO4aAEzNnStlgq3gBSQFb2BV3Zkr0dz2+P+Z93nQnU3c4aJt7buDGuly1KhBqUxahD6z2MUQrL5f+k5Bt2yT7Cg5qcG85DYkCwiEfUHFW5iUkYacQASbstIR4eq6EOFj1BnbXkna+dpZB6HB5HzN71kHpAzcTpJAIEcs5N+NjrIFtBX5b2lIO4z2eRsOFnT0ctjvpUotZnkmq1QcsDZ/0Wj9Iasr9v+4nhiTswMEEWRbn1UaE22UmZpTUOdMNqPAuTp5O+mjc3kFJk3Ei/Qw=
  app: signup5-dev
  on:
    repo: Signup5/signup5
