language: java
jdk:
- oraclejdk13
services:
- docker
before_install:
- chmod +x gradlew
- docker pull postgres
- docker run --name pg_signup5 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password
  -e POSTGRES_DB=signup -p 5432:5432 -d postgres:12
deploy:
  provider: heroku
  api_key:
    secure: dpuSsMbifkvBQ1kUZ7fTp2gxUuES34SQVMvcyCQBXmmdKIOtxeEuGmiYSSvOfWYh4+7x4mNhC9TGgCI93QYHveGZwuU9Zz3N9vxdhWBwO+pGoCp3jvpQTq+cyUt13bKPKg6LxNfgGb5kC/L1V/MDlDqTqrq+sAjn6dYaseuz05h7ayD95uszlzHFiLfygTePffXedVUBA9oBwbHnnm1Z2Yebe0wOREeoVY8K/Hb38c5iZjAyc2O+ExIMnOioIoNbvprAVI3NeT+nr5gRTpOCei+K1rkrQLkgxTvQq6LE+pIXROsUo1n0sTdKpPqJ/wSKowkdr8d20We4G+7S5a0cu65Y/nGFJkHmzq7C2AhI7o8PLWxq3ZGSzBGwXSbkl+qFoPmblog8pkMaCtpqCRTjbXwpC0UYGpIHYaoA10AUCJVZbXPtP/vPCcYbh+gqudOHpu4medWKpfRP9RyLfAE1sjhWO9SokCLlhx13bM8kGSwTbvaPHrfTS+mMfOoVGjLbPYNcOdEBbrASsBVLczlILJjBFNutqmem+QjSWRfCpOYEm5ciw1eSssB9TvvwsvpSWUx2+zlNrhpLU+xCRnyslfJk1OWl7TzI9vcAP6gRBw/a0AQo3lXn6QxOFMekHJR0OxUM4qzXMdCgbz93w0j5yK9Z8hKqrY5ydgUEOBt7z6I=
