spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}


#graphql:
#  datetime:
#    scalars:
#      date:
#        scalarName: MyDate
#      localDate:
#        scalarName: MyLocalDate
#      localDateTime:
#        scalarName: MyLocalDateTime
#      localTime:
#        scalarName: MyLocalTime
#      offsetDateTime:
#        scalarName: MyOffsetDateTime